Project explorer now shows the project tree
PipeRift/rift pull request #4
Opened 2021-02-19 18:59 UTC by Tharrik

2021-02-19 19:27 UTC, muit requested changes

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Include/Editors/Projects/FileExplorerPanel.h
> +struct File
Should be contained inside FileExplorer instead of global space

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Include/Editors/Projects/FileExplorerPanel.h
> +struct Folder
Same

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +		CreateFolderNode(projectFolder);
Nice encapsulation

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +
new line not needed

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +		String st = FileSystem::ToString(relative);
don't use cryptic variable names

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +				String name = FileSystem::ToString(*it);
can be constant

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +		static String extension = ".rf";
Can be StringView

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +					for(size_t i = 0; !exists && i < current->folders.Size(); ++i)
use i32 for index iterators (99.9% of the times)

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +						if(folder->name == name)
No need to dereference into a pointer. Use the reference directly until you assign `current = &folder`

2021-02-19 19:27 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +					for(size_t i = 0; !exists && i < current->folders.Size(); ++i)
Also, don't put complicated conditions inside the for loop. It makes it hard to understand the logic behind iteration.
Use an if inside.

2021-02-22 12:39 UTC, muit commented
Merge from main to solve the linux build :)

2021-02-22 14:25 UTC, Tharrik commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +
New line?

2021-02-22 14:30 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +
Just that line 75 can be removed

2021-02-22 14:42 UTC, Tharrik commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +					for(size_t i = 0; !exists && i < current->folders.Size(); ++i)
The !exists condition is needed to end the for loop when the file has been found. I don't think I can remove it from the conditions.

2021-02-22 14:51 UTC, Tharrik commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +
I tend to leave a new line before statements like for or if to let the code breathe and make it more readable. Although it's not a consistent rule for me. 🤔

2021-02-22 14:53 UTC, Tharrik commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
>  	// Directories
I just noticed this: Why the use of a anonymous block code?

2021-02-22 15:39 UTC, muit commented on Apps/Editor/Src/Editors/Projects/FileExplorerPanel.cpp
> +
Fair enough! :)

2021-02-22 17:16 UTC, Tharrik commented
All changes done in the next commit

2021-02-23 16:49 UTC, merged